services:
  portfolio:
    build:
      context: .
    image: portfolio-app:latest
    container_name: portfolio-app
    environment:
      APP_BIND_ALL: ${APP_BIND_ALL:-true}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      CLIENT_ID_KEY: ${CLIENT_ID_KEY}
      CLIENT_SECRET_KEY: ${CLIENT_SECRET_KEY}
      GOOGLE_CONNECTION_TABLE_NAME: ${GOOGLE_CONNECTION_TABLE_NAME}
      LOG_ADD_SOURCE: ${LOG_ADD_SOURCE:-false}
      LOG_FORMAT: ${LOG_FORMAT:-json}
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LPS_SESSION_KEY: ${LPS_SESSION_KEY}
    ports:
      - "8080:8080"
    restart: unless-stopped
